use_frameworks!

target 'CarambaKit_Tests' do
  pod 'CarambaKit', :path => '../'
  pod 'CarambaKit/Networking', :path => '../'
  pod 'CarambaKit/Persistence', :path => '../'
  pod 'Quick', "~> 0.10"
  pod 'Nimble', '~> 5.0'
  pod 'OHHTTPStubs', "5.2.1"
  pod 'OHHTTPStubs/Swift', "5.2.1"
end