require 'versionomy'

COMMIT_MESSAGE = "Bump podspec to"

lane :pods do
  cocoapods(podfile: "Example/")
end

lane :tests do
  scan(workspace: "Example/CarambaKit.xcworkspace", scheme: "CarambaKit_Tests", clean: true)
end

lane :travis do
  pods
  tests
  pod_lib_lint(allow_warnings: true, verbose: false)
end
  
lane :push do
  podspec = "CarambaKit.podspec"
  last_version = version_get_podspec(path: podspec)
  version = version_bump_podspec(path: podspec)
  git_commit(path: [podspec, "./Example/Podfile.lock"], message: "#{COMMIT_MESSAGE} #{version}")
  changelog = changelog_from_git_commits(between: [last_version, 'HEAD'])
  changelog ||= "No changelog"
  github_release = set_github_release(
    repository_name: "carambalabs/CarambaKit",
    api_token: ENV['GITHUB_TOKEN'],
    name: version,
    tag_name: version,
    description: changelog,
    commitish: "master"
  )
  push_to_git_remote(remote_branch: 'master', force: false, tags: true)
  pod_push(allow_warnings: true, verbose: true)
  pod_push(path: podspec, verbose:true, allow_warnings: true, repo: 'carambalabs', sources: ['https://github.com/carambalabs/Specs', 'https://github.com/CocoaPods/Specs'])
end
